/*
 * projecteuler.c
 *
 *  Created on: 11 nov. 2017
 *      Author: Erik
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <strings.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
#include <stdlib.h>

#if 0
/* Problem 1
Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
 */

int main(void)
{
	unsigned long sum = 0;
	unsigned int i = 1, ceiling = 1000;

	for(i = 1; i < ceiling; i++)
	{
		if(i%3 == 0 || i%5 == 0)
		{
			sum += i;
		}
	}

	printf("%lu",sum);

	return 0;
}

#endif

#if 0
/* Problem 2
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

int main(void)
{
	unsigned long before = 0, now = 1, temp = 0, sum = 0;

	while(now+before < 4000000)
	{
		temp = now;
		now += before;
		before = temp;

		if(now%2 == 0)
		{
			sum += now;
		}
	}

	printf("%lu\n",sum);

	return 0;
}
#endif

#if 0
/* Problem 3
Largest prime factor
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
*/

unsigned long long sum(const unsigned long long *x)
{
	unsigned long long sum = 0;
	while(*x)
	{
		sum += *x;
		x++;
	}
	return sum;
}

int main(void)
{
	unsigned long long factors[1000] = {0}, i = 2, number = 9009;
	unsigned int counter = 0;

	while(sum(factors) < number)
	{
		if(number%i == 0)
		{
			factors[counter] = i;
			number /= i;
			counter++;
		}
		i++;
	}

	for(i = 0; i < counter; i++)
	{
		printf("%llu\n",factors[i]);
	}

	printf("Last = %llu\n",factors[counter-1]);
	getchar();

	return 0;
}

#endif

#if 1
/*Problem 4
Largest palindrome product
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.
*/
bool isPalin(unsigned long input)
{
	bool result = 0;
	unsigned long original = input;
	int i = 1, length = 0;
	while(input/(10*i)>1)
	{
		length++;
		i++;
	}
	char temp[length];
	for(i = 0; i < length; i++)
	{
		temp[i] = input%10 + '0';
		input /= 10;
	}
	if(atol(temp) == original)
	{
		result = 1;
	}
	return result;
}

int main(void)
{
	unsigned long a = 9009;

	printf("%i",isPalin(a));
	return 0;
}

#endif
